### ISSUE TITLE
请问https://qiutc.me/这个预览的网站theme是什么呢？

### ISSUE THREAD

**Issue by itgoyo** [TongchengQiu/hexo-theme-another#9]
想问问https://qiutc.me/   
这个预览的网站theme是什么呢，进去感觉和another完全不一样，但是这个简约风格好喜欢。是hexo搭建的还是workpress？

**Comment by TongchengQiu** [comment]
hello，这个主题是基于 hexo 的主题，主要是因为我很喜欢 kindle，因此设计了这么一套风格，暂时还没有开源呢。
